const loc = 'assets/icons/fa5.15.1',
  spec = {
    regular: [
      'address-card',
      'ballot-check',
      'bars',
      'bold',
      'brackets',
      'brackets-curly',
      'browser',
      'calendar',
      'caret-left',
      'caret-down',
      'check',
      'check-circle',
      'chevron-left',
      'chevron-double-left',
      'chevron-down',
      'clock',
      'code',
      'cog',
      'cogs',
      'copy',
      'envelope-open-text',
      'exclamation-triangle',
      'exclamation-circle',
      'edit',
      'file',
      'file-code',
      'file-exclamation',
      'file-invoice',
      'file-plus',
      'file-times',
      'filter',
      'folder',
      'folder-open',
      'folder-plus',
      'folder-times',
      'folder-tree',
      'folders',
      'font-case',
      'globe-americas',
      'grip-vertical',
      'history',
      'hourglass-half',
      'info',
      'italic',
      'plus',
      'plus-circle',
      'question-circle',
      'ruler-triangle',
      'save',
      'search',
      'strikethrough',
      'tasks',
      'text-width',
      'times',
      'tint',
      'trash-alt',
      'underline',
      'undo-alt',
      'user',
      'window-close',
    ],
    light: [
      'atom-alt',
      'check-square',
      'folder-open',
      'sort',
      'sort-up',
      'square',
    ],
    solid: [
      'check-square',
      'engine-warning',
      'exclamation-triangle',
      'globe',
      'sign-out-alt',
      'times-octagon',
      'user',
      'user-friends',
    ],
  },
  res = 'fa-icons.js',
  template = 'app/fa-icons.txt';

module.exports = { loc, res, spec, template};
